apiVersion: v1
kind: Secret
metadata:
  name: private-bgd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Santhosh-shark/sk-argocd.git
  password: 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
  username: Santhosh-shark