---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-alpha
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/Santhosh-shark/sk-argocd.git
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: jenkins
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-alpha
  namespace: argocd
spec:
  project: project-alpha
  source:
    repoURL: https://github.com/Santhosh-shark/sk-argocd.git
    targetRevision: master
    path: demoapp
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
