apiVersion: v1
kind: Secret
metadata:
  name: private-bgd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/kirupakaran369/agrocd-demo.git
  password: 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
  username: kirupakaran369